export const ADD_INGREDIENT = 'ADD-INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENT = 'SET_INGREDIENT';
export const IF_THERE_NO_INGREDIENTS = 'IF_THERE_NO_INGREDIENTS';