export const ADD_INGREDIENT = 'ADD-INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENT = 'SET_INGREDIENT';
export const IF_THERE_NO_INGREDIENTS = 'IF_THERE_NO_INGREDIENTS';

//this for order data or form input field
export const START_ORDERING = 'START_ORDERING';
export const ORDER_SUCCESSFUL = 'ORDER_SUCCESSFUL';
export const ORDER_FAIL = 'ORDER_FAIL';
export const ORDER_SUMMARY_PAGE = 'ORDER_SUMMARY_PAGE';

//fetching data from server 
export const INITIAL_ORDER_FITCH_START = 'INITIAL_ORDER_FITCH_START';
export const INITIAL_ORDER_FITCH_SUCCESSFUL = 'INITIAL_ORDER_FITCH_SUCCESSFUL';
export const INITIAL_ORDER_FITCH_FAIL = 'INITIAL_ORDER_FITCH_FAIL';

//action for user authentication
export const USER_AUTH_START = 'USER_AUTH_START';
export const USER_AUTH_SUCCESSFUL = 'USER_AUTH_SUCCESSFUL';
export const USER_AUTH_FAIL = 'USER_AUTH_FAIL';
export const USER_AUTH_LOGOUT = 'USER_AUTH_LOGOUT ';
